pkg_name=tmux
pkg_origin=lilian
pkg_version=2.2
pkg_description="A terminal multiplexer"
pkg_upstream_url=https://tmux.github.io/
pkg_license=('MIT')
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_source="https://github.com/tmux/tmux/releases/download/${pkg_version}/tmux-${pkg_version}.tar.gz"
pkg_shasum=bc28541b64f99929fe8e3ae7a02291263f3c97730781201824c0f05d7c8e19e4
pkg_deps=(core/glibc core/libevent lilian/ncurses)
pkg_build_deps=(lilian/gcc lilian/make)
pkg_bin_dirs=(bin)
