#!/bin/bash

exec 2>&1

echo "Starting Apache Tomcat"

if path={{pkgPathFor "lilian/jdk8"}}; then
  export JAVA_HOME=$path
elif path={{pkgPathFor "lilian/jdk7"}}; then
  export JAVA_HOME=$path
fi
if [ -z ${JAVA_HOME+x} ]; then
  echo "Cannot start Tomcat without lilian/jdk8 or lilian/jdk7"
  exit 1
fi

export TOMCAT_HOME="{{pkg.svc_var_path}}/tc"
export CATALINA_OPTS="{{cfg.server.catalina-opts}}"

echo "Executing Tomcat here: ${TOMCAT_HOME}/bin/catalina.sh"
exec ${TOMCAT_HOME}/bin/catalina.sh run
