version: '2'
services:
  zookeeper:
    image: lilian/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: lilian/kafka
    links:
      - zookeeper
    command: start lilian/kafka --peer zookeeper --bind zookeeper:zookeeper.default
